name = "jotbird-backend"
main = "src/index.ts"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "jotbird-db"
database_id = "DATABASE_ID_HERE"

[triggers]
crons = ["0 3 * * *"]
